import React, { useState } from "react";
import { DiagnosticResult, RecommendationTask, SupplierItem } from "../types";
import { 
  FileText, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  CheckCircle, 
  Sparkles, 
  Globe2, 
  Briefcase, 
  AlertOctagon, 
  Clock 
} from "lucide-react";

interface ReportGeneratorProps {
  diagResult: DiagnosticResult;
  tasks: RecommendationTask[];
  organizationName: string;
  sector: string;
  userRole: string;
}

type ReportType = 
  | "onePageDiagnostic"
  | "riskSummary"
  | "improvementRoadmap"
  | "supplierScreening"
  | "managementDeck"
  | "bilingualSummary";

export default function ReportGenerator({
  diagResult,
  tasks,
  organizationName = "Our Organization",
  sector = "General Technology",
  userRole = "Corporate ESG Manager"
}: ReportGeneratorProps) {
  const [activeReport, setActiveReport] = useState<ReportType>("onePageDiagnostic");
  const [copied, setCopied] = useState(false);

  const org = organizationName || "Our Organization";

  // Calculate stats for reporting
  const completedTasksCount = tasks.filter((t) => t.status === "Completed").length;
  const pendingTasksCount = tasks.filter((t) => t.status !== "Completed").length;
  const totalTasksCount = tasks.length;
  const completionRate = totalTasksCount > 0 ? Math.round((completedTasksCount / totalTasksCount) * 100) : 0;

  // Retrieve temporary supplier details for Supplier Screening report fallback
  const getSuppliersText = () => {
    try {
      const saved = localStorage.getItem("esg_suppliers");
      if (saved) {
        const parsed: SupplierItem[] = JSON.parse(saved);
        if (parsed.length > 0) {
          return parsed.map(s => `- ${s.name} (${s.country}): Carbon Intensity ${s.carbonIntensity}, Labor Audited: ${s.laborStandardCertified ? "YES" : "NO"}, Ethical: ${s.corporateEthicsCode ? "YES" : "NO"}`).join("\n");
        }
      }
    } catch (e) {}
    return "- Apex Logistics (Germany): Carbon High, Labor SA8000 Certified: YES, Anti-Bribery safeguards: YES\n- Pacific Tech Hardware (Taiwan): Carbon Medium, Labor SA8000 Certified: NO, Anti-Bribery safeguards: YES";
  };

  // Generate dynamic, beautiful reports structurally based on active state parameters
  const getReportPayload = (): { title: string, text: string } => {
    switch (activeReport) {
      case "onePageDiagnostic":
        return {
          title: "One-Page ESG Diagnostic Report",
          text: `========================================================================
                      ESG PERFORMANCE DIAGNOSTIC REPORT
========================================================================
ORGANIZATION: ${org}
SECTOR:       ${sector}
ASSESSMENT:   Audited and compiled: ${new Date().toLocaleDateString()}
AUDITOR:      ${userRole} (AI ESG Advisor Agent™)
------------------------------------------------------------------------

I. ACCUMULATIVE SCORE INDEX
- Overall ESG Score:          ${diagResult.scores.overall}%
- Environmental Pilar (E):    ${diagResult.scores.environmental}%
- Social Pilar (S):           ${diagResult.scores.social}%
- Governance Pilar (G):       ${diagResult.scores.governance}%
- Compliance Readiness Index: ${diagResult.complianceReadinessScore || 48}%
- ESG Data Completeness Index:${diagResult.dataCompletenessLevel || 55}%
- Sourcing Carbon Maturity:   ${diagResult.carbonManagementMaturity || "Beginner"}

II. AUTOMATED COMPLIANCE GAP ANALYSIS
${diagResult.complianceGap}

III. CORE ORGANIZATIONAL STRENGTHS
${diagResult.strengths.map((s, idx) => `${idx + 1}. [STRENGTH] ${s}`).join("\n")}

IV. CORE GAPS & RISKS INVENTORY
${diagResult.gaps.map((g, idx) => `${idx + 1}. [GAP FLAG] ${g}`).join("\n")}

V. STRATEGIC EXPLAINER
${diagResult.plainLanguageExplanation || "Assessment in progress. Perform detailed self-governance audit to formulate dynamic organizational statements."}

VI. EXECUTIVE SUMMARY
${diagResult.professionalSummary || "remitting critical gaps regarding direct grid power tracking and independent staff composition will maximize public rating scores immediately."}
------------------------------------------------------------------------
Generated by ESG Advisor Agent, compliant with GRI and CSRD standards.`
        };

      case "riskSummary":
        return {
          title: "Comprehensive ESG Risk Summary",
          text: `========================================================================
                      COMPREHENSIVE ESG RISK SUMMARY
========================================================================
ORGANIZATION: ${org}
SECTOR:       ${sector}
DATE:         ${new Date().toLocaleDateString()}
CLASSIFICATION: CONFIDENTIAL
------------------------------------------------------------------------

1. REGULATORY COMPLIANCE EXPOSURE
${diagResult.complianceGap}

2. ENVIRONMENTAL (E) RISK REGISTER
- Direct utility emissions tracking is currently evaluated as: [${diagResult.scores.environmental < 50 ? "CRITICAL RISK" : "MINIMIZED RISK"}]
- Identified gaps: ${diagResult.gaps.filter(g => g.toLowerCase().includes("carbon") || g.toLowerCase().includes("emission") || g.toLowerCase().includes("waste")).join(", ") || "No direct emissions calculation listed."}
- Risk Trigger: Lacking verifiable Scope 1/2 baselines triggers compliance non-alignment under EU CSRD climate disclosure guidelines.

3. SOCIAL (S) REPUTATION & SAFETY LABILITIES
- Diversity metrics and safety review structures computed overall: ${diagResult.scores.social}%
- Safety and welfare risks include potential pay discrepancies or unverified workplace anonymous avenues, affecting social sustainability trust indices.

4. GOVERNANCE (G) TRANSPARENCY LIABILITIES
- Executive authority independence is categorized as: [${(diagResult.scores.governance) < 50 ? "LEVEL HIGH RISK" : "ADEQUATE"}]
- Target conflict policies and disclosure parameters: Board autonomy must increase beyond 50% to prevent stakeholder transaction conflicts.

5. EXTERNAL SUPPLY CHAIN (SCOPE 3) RISKS: [${diagResult.supplierEsgRiskLevel || "Medium"} Risk Level]
- Relying on non-certified third-party logistics firms without signed anti-corruption rules exposes the company to indirect labor standard liabilities.

------------------------------------------------------------------------
Recommended Remediation: Please consult the 90-Day Tactical Improvement Roadmap to resolve flagged structural liabilities.`
        };

      case "improvementRoadmap":
        const highPriorityTasks = tasks.filter(t => t.priority === "High");
        const medPriorityTasks = tasks.filter(t => t.priority === "Medium");
        const lowPriorityTasks = tasks.filter(t => t.priority === "Low");
        
        return {
          title: "90-Day ESG Improvement Roadmap",
          text: `========================================================================
                 90-DAY ESG STRATEGIC Remodeling ROADMAP
========================================================================
ORGANIZATION: ${org}
TRACK CYCLE:  90 Days Continuous Improvement (SMS Actions)
DATE:         ${new Date().toLocaleDateString()}
------------------------------------------------------------------------

PHASE I: DAYS 1 - 30 (CRITICAL COMPLIANCE REMEDIATION)
Focus: Highly urgent regulatory alignments and Scope baseline setups.

${highPriorityTasks.length > 0 ? highPriorityTasks.map((t, idx) => `[TASK ${idx+1}] ${t.title}
  Pilar:        ${t.pilar === 'E' ? 'Environmental' : t.pilar === 'S' ? 'Social' : 'Governance'}
  Priority:     HIGH IMPORTANCE
  Action:       ${t.action}
  KPI Target:   (${t.impact})
  Assignee:     ${t.assignee || 'Unassigned / ESG Committee'}
  Deadline:     Day 25`).join("\n\n") : "- Establish Scope 1 & Scope 2 baseline calculations by auditing raw energy logs.\n- Adopt binding board conflict policies."}

------------------------------------------------------------------------
PHASE II: DAYS 31 - 60 (OPERATIONAL COMPLIANCE EXPANSION)
Focus: Addressing medium-priority items, training staff, and coordinating supplier audits.

${medPriorityTasks.length > 0 ? medPriorityTasks.map((t, idx) => `[TASK ${idx+1}] ${t.title}
  Pilar:        ${t.pilar === 'E' ? 'Environmental' : t.pilar === 'S' ? 'Social' : 'Governance'}
  Priority:     MEDIUM
  Action:       ${t.action}
  KPI Target:   (${t.impact})
  Assignee:     ${t.assignee || 'Staff Lead'}
  Deadline:     Day 50`).join("\n\n") : "- Deploy Supplier Ethics Mandate to active screen checklists.\n- Perform gender-pay gap balance audits."}

------------------------------------------------------------------------
PHASE III: DAYS 61 - 90 (CONTINUOUS COMPLIANCE ENGAGEMENT)
Focus: Strengthening governance transparency, waste recycle protocols, and local sponsorships.

${lowPriorityTasks.length > 0 ? lowPriorityTasks.map((t, idx) => `[TASK ${idx+1}] ${t.title}
  Pilar:        ${t.pilar === 'E' ? 'Environmental' : t.pilar === 'S' ? 'Social' : 'Governance'}
  Priority:     LOW/MAINTENANCE
  Action:       ${t.action}
  KPI Target:   (${t.impact})
  Assignee:     ${t.assignee || 'Sustainability Director'}
  Deadline:     Day 85`).join("\n\n") : "- Expand local community charities sponsorship.\n- Formulate circular plastic recycle plans."}

------------------------------------------------------------------------
SMS TRACK PROGRESS SUMMARY:
- Registered Action Items:  ${totalTasksCount} tasks
- Remodeled Completed:      ${completedTasksCount} goals (${completionRate}%)
- Pending Goals:            ${pendingTasksCount} remaining`
        };

      case "supplierScreening":
        return {
          title: "Supplier ESG Screening Report",
          text: `========================================================================
                    SUPPLIER ESG RISK & SCREENING REPORT
========================================================================
PROCURING ORGANIZATION: ${org}
AUDITOR AUDIT TRACK:    Scope 3 Supply Chain Disclosures
DATE:                   ${new Date().toLocaleDateString()}
------------------------------------------------------------------------

1. SOURCING VULNERABILITY CONTEXT
Operating in the '${sector}' sphere demands high accountability regarding vendor material sourcing. Lacking supply chain checks induces heavy brand liabilities.

2. LISTED SUPPLIERS SCREENING INVENTORY
${getSuppliersText()}

3. COMPREHENSIVE SUPPLY MATRIX AUDIT
- Raw Supplier Risk Rating:  [${diagResult.supplierEsgRiskLevel || "Medium"} Risk Index]
- Labor Standards Index:    Verify if vendors maintain SA8000 credentials. Uncertified vendors represent high reputation concerns.
- Anti-Corruption Mandate:  All contractors must submit signed compliance disclosures to protect the purchasing board.

4. PROCUREMENT ACTION STEPS
- Distribute standard 'Sustainability and Transparency Disclosure requests' to underperforming vendors.
- Gradually transition purchasing quota toward ISO 14001 or SA8000 certified logistic fleets.

------------------------------------------------------------------------
Report compiled with ESG supplier screening agents.`
        };

      case "managementDeck":
        return {
          title: "ESG Briefing - Management Deck Summary",
          text: `========================================================================
                     BOARD BRIEFING: STRATEGIC ESG SUMMARY
========================================================================
ORGANIZATION: ${org}
PREPARED BY:  ${userRole}
AUDIT TIMESTAMP: ${new Date().toLocaleDateString()}
------------------------------------------------------------------------

SLIDE 1: OBJECTIVE & BUSINESS CASE
* Objective: Deliver structured ESG diagnostic analysis to satisfy investor expectations and future CSRD regulatory rules in the ${sector} industry.
* Strategic Drivers: Avoid standard litigation fines, reduce operational waste, and lift corporate governance profile to access sustainability-linked bank credits.

SLIDE 2: CURRENT PERFORMANCE PROFILE
* Accumulative Rating:       ${diagResult.scores.overall}% (Developing status)
* Environmental (E) Score:    ${diagResult.scores.environmental}%
* Social (S) Score:           ${diagResult.scores.social}%
* Governance (G) Score:       ${diagResult.scores.governance}%
* Climate Compliance:         ${diagResult.complianceReadinessScore || 48}% Readiness Ratio
* Carbon Maturity Stage:      ${diagResult.carbonManagementMaturity || "Beginner"}

SLIDE 3: IDENTIFIED CORPORATE STRENGTHS
${diagResult.strengths.slice(0, 3).map((s, idx) => `* [STRENGTH ${idx+1}] ${s}`).join("\n")}

SLIDE 4: PENDING VULNERABILITIES & COMPLIANCE GAPS
${diagResult.gaps.slice(0, 3).map((g, idx) => `* [GAP FLAG ${idx+1}] ${g}`).join("\n")}
* Risk Index: Regulatory friction risks with traditional EU/SEC carbon regulations.

SLIDE 5: 90-DAY STRATEGIC ROADMAP REMEDIATION
* Phase I (Days 1-30): Establish Scope 1/2 baselines, adopt board disclosures.
* Phase II (Days 31-60): Standardize supplier screenings, gender pay review.
* Phase III (Days 61-90): Complete staff training, formalize circular recycling.

------------------------------------------------------------------------
End of Briefing Presentation Summary.`
        };

      case "bilingualSummary":
        return {
          title: "Bilingual Executive Summary / 双语执行摘要",
          text: `========================================================================
              BILINGUAL ESG EXECUTIVE SUMMARY / 双语ESG执行摘要
========================================================================
ORGANIZATION / 机构名称:   ${org}
DATE / 编制日期:         ${new Date().toLocaleDateString()}
STANDARDS / 符合标准:     GRI, SASB, CSRD
------------------------------------------------------------------------

■ ENGLISH SECTION / 英文阐述

1. PERFORMANCE RATINGS
- Accumulated Rating Score: ${diagResult.scores.overall}%
- Environmental Pilar (E):  ${diagResult.scores.environmental}%
- Social Pilar (S):         ${diagResult.scores.social}%
- Governance Pilar (G):     ${diagResult.scores.governance}%
- Compliance Readiness:     ${diagResult.complianceReadinessScore || 48}%

2. DIAGNOSTIC INTERPRETATION
The organization is in the 'Developing' phase. While employee welfare programs and initial codes of conduct are solid, the lack of third-party audited Scope 1 and Scope 2 utility calculations constitutes a primary risk indicator for compliance reporting.

3. IMMEDIATE PRIORITIES
- Execute detailed baseline carbon footprints for Scope 1 and Scope 2 energy logs.
- Lift independent board advisory seats past 50% to prevent transactional conflict.


------------------------------------------------------------------------
■ CHINESE SECTION / 中文阐述

1. 业绩评分与评级
- 综合 ESG 绩效得分:        ${diagResult.scores.overall}%
- 环境支柱得分 (E):         ${diagResult.scores.environmental}%
- 社会责任得分 (S):         ${diagResult.scores.social}%
- 公司治理得分 (G):         ${diagResult.scores.governance}%
- 合规就绪率:              ${diagResult.complianceReadinessScore || 48}%

2. 诊断性评估与解读
受评估组织当前处于“发展建设”阶段。虽然在员工福利保障和初步行为准则建设方面表现扎实，但由于缺乏经第三方审计的范围 1（Scope 1 直接排放）和范围 2（Scope 2 间接用能排放）能耗核算，给将来的可持续合规申报留下了重大的战略合规隐患。

3. 紧迫整改任务优先项
- 收集企业自身的用电与天然气能耗收据，建立范围 1 和范围 2 温室气体排放基准。
- 将董事会成员或高级顾问团队中的独立席位比例提升至 50% 以上，以规避潜在关联交易冲突。

========================================================================`
        };

      default:
        return { title: "", text: "" };
    }
  };

  const currentReport = getReportPayload();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentReport.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([currentReport.text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${currentReport.title.toLowerCase().replace(/ /g, "_")}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCSV = () => {
    const csvRows = [
      ["Metric/Task Parameter", "Value/Detail", "Pillar", "Status/Rating"],
      ["Organization Name", org, "General", "N/A"],
      ["Industry Sector", sector, "General", "N/A"],
      ["Created Date", new Date().toLocaleDateString(), "General", "N/A"],
      ["Overall ESG Score", `${diagResult.scores.overall}%`, "General", "Active"],
      ["Environmental (E) Rating", `${diagResult.scores.environmental}%`, "E", "Active"],
      ["Social (S) Rating", `${diagResult.scores.social}%`, "S", "Active"],
      ["Governance (G) Rating", `${diagResult.scores.governance}%`, "G", "Active"],
      ["Compliance Readiness Score", `${diagResult.complianceReadinessScore || 48}%`, "General", "Active"],
      ["Supplier ESG Risk Level", diagResult.supplierEsgRiskLevel || "Medium", "Social/Supply", "Active"],
      ["Carbon Maturity Level", diagResult.carbonManagementMaturity || "Beginner", "Environmental", "Active"],
      ["", "", "", ""],
      ["Strategic Improvement Tasks", "", "", ""],
      ["ID", "Title", "Pillar", "Priority", "Status", "Impact"]
    ];

    tasks.forEach((t) => {
      csvRows.push([t.id, t.title, t.pilar, t.priority, t.status, t.impact]);
    });

    const csvContent = "data:text/csv;charset=utf-8," 
      + csvRows.map(e => e.map(val => `"${String(val).replace(/"/g, '""')}"`).join(",")).join("\n");
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.href = encodedUri;
    link.download = `${org.toLowerCase().replace(/ /g, "_")}_esg_audit_metrics.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadPresentation = () => {
    const mainDeck = `========================================================================
PRESENTATION SUMMARY SEEDS: ${org.toUpperCase()} ESG BRIEFING
========================================================================
Generated on: ${new Date().toLocaleDateString()}
Theme: Sustainability & Governance Management Framework compliance

${currentReport.text}
`;

    const blob = new Blob([mainDeck], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${org.toLowerCase().replace(/ /g, "_")}_presentation_deck.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6" id="esg-report-generator">
      {/* Hero Intro */}
      <div className="bg-gradient-to-r from-emerald-950 to-slate-900 rounded-2xl p-6 md:p-8 text-white relative overflow-hidden border border-emerald-900">
        <div className="absolute top-0 right-0 w-80 h-80 bg-emerald-600/10 rounded-full blur-3xl pointer-events-none" />
        <div className="space-y-2">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-800/60 text-emerald-250 border border-emerald-700/50">
            <FileText className="w-3.5 h-3.5 text-emerald-400" /> Executive Deliverables
          </span>
          <h2 className="text-xl md:text-2xl font-bold tracking-tight">Dynamic ESG Report Generator</h2>
          <p className="text-emerald-100/80 text-sm max-w-2xl">
            Compile your regulatory compliance audits, continuous tracking KPIs, and active roadmaps into structured reports for board reviews, supply chain inquiries, or green bank disclosures.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        
        {/* Navigation Sidebar Selector */}
        <div className="lg:col-span-1 bg-white rounded-2xl border border-gray-155 p-4 shadow-xs h-fit space-y-2">
          <span className="text-[10px] uppercase font-extrabold text-gray-400 block px-2.5 pb-2">Select Report Asset</span>
          
          <button
            onClick={() => setActiveReport("onePageDiagnostic")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "onePageDiagnostic" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            1. One-Page Diagnostic
          </button>

          <button
            onClick={() => setActiveReport("riskSummary")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "riskSummary" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            2. Comprehensive Risk Summary
          </button>

          <button
            onClick={() => setActiveReport("improvementRoadmap")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "improvementRoadmap" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            3. 90-Day Tactical Roadmap
          </button>

          <button
            onClick={() => setActiveReport("supplierScreening")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "supplierScreening" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            4. Supplier Sourcing Screening
          </button>

          <button
            onClick={() => setActiveReport("managementDeck")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "managementDeck" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            5. Executive Management Deck
          </button>

          <button
            onClick={() => setActiveReport("bilingualSummary")}
            className={`w-full px-3.5 py-2.5 rounded-xl text-left text-xs font-bold block transition-all ${
              activeReport === "bilingualSummary" 
                ? "bg-emerald-800 text-white shadow-sm"
                : "text-gray-650 hover:bg-gray-50 bg-transparent"
            }`}
          >
            6. Bilingual Executive Summary
          </button>

          <div className="p-3 bg-emerald-50/40 rounded-xl border border-emerald-100 text-[10px] text-emerald-850 pt-3 leading-normal font-medium">
            <span className="font-extrabold uppercase block mb-0.5">Continuous Compliance</span>
            These documents compile quantitative utility tracker variables and completed milestones database in real-time.
          </div>
        </div>

        {/* Live Presentation Panel */}
        <div className="lg:col-span-3 bg-white rounded-2xl border border-gray-155 p-6 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b border-gray-100 pb-4 gap-4">
            <div>
              <h3 className="font-bold text-gray-950 text-base flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-emerald-700" /> {currentReport.title}
              </h3>
              <p className="text-xs text-gray-400">Verifiably formatted text ready for executive reports or stakeholders download.</p>
            </div>

            <div className="flex flex-wrap items-center gap-1.5 shrink-0">
              <button
                onClick={handleCopy}
                className="px-2.5 py-1.5 rounded-lg border border-gray-200 text-xs text-gray-600 bg-white hover:bg-gray-50 font-bold inline-flex items-center gap-1 transition-colors cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" /> Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" /> Copy
                  </>
                )}
              </button>

              <button
                onClick={handleDownload}
                className="px-2.5 py-1.5 rounded-lg text-xs font-bold border border-gray-200 text-gray-600 bg-white hover:bg-gray-50 inline-flex items-center gap-1 transition-colors cursor-pointer"
                title="Download report as descriptive TXT"
              >
                <Download className="w-3.5 h-3.5" /> TXT
              </button>

              <button
                onClick={handleDownloadCSV}
                className="px-2.5 py-1.5 rounded-lg text-xs font-bold border border-emerald-100 text-emerald-800 bg-emerald-50 hover:bg-emerald-100 inline-flex items-center gap-1 transition-colors cursor-pointer"
                title="Download raw performance data and checklist tasks as CSV"
              >
                <Download className="w-3.5 h-3.5" /> Export CSV
              </button>

              <button
                onClick={handleDownloadPresentation}
                className="px-2.5 py-1.5 rounded-lg text-xs font-bold border border-gray-200 text-purple-800 bg-purple-50 hover:bg-purple-100 inline-flex items-center gap-1 transition-colors cursor-pointer"
                title="Download presentation slide outline summary"
              >
                <FileText className="w-3.5 h-3.5" /> Export Slide Deck
              </button>

              <button
                onClick={handlePrint}
                className="px-2.5 py-1.5 rounded-lg text-xs font-bold border border-emerald-800 bg-emerald-800 text-white hover:bg-emerald-950 inline-flex items-center gap-1 transition-colors cursor-pointer"
              >
                <Printer className="w-3.5 h-3.5" /> Export PDF (Print)
              </button>
            </div>
          </div>

          {/* Live Editor Block */}
          <div className="bg-slate-950 border border-slate-900 rounded-2xl p-6 font-mono text-[11px] md:text-xs text-slate-200 overflow-x-auto leading-relaxed max-h-[500px] overflow-y-auto whitespace-pre scrolling-touch relative selection:bg-emerald-800">
            <div className="absolute top-2 right-3 text-[9px] uppercase font-bold text-slate-500 font-sans tracking-wide">Copy-paste ready</div>
            {currentReport.text}
          </div>
        </div>
      </div>
    </div>
  );
}
